version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

volumes:
  mongo_data: 